ClaseBase_CrudProject/ClaseBase_CrudProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls')),

]

ClaseBase_CrudProject/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
app_name="first_app"

urlpatterns=[
    path('',views.index.as_view(),name="index"),
    path('addmusician/',views.addmusician.as_view(),name="addmusician"),
    path('addalbum/',views.addalbum.as_view(),name="addalbum"),
    path('Musiciandetails/<pk>/',views.Musiciandetails.as_view(),name="Musiciandetails"),
    path('updatemusician/<pk>/',views.updatemusician.as_view(),name="updatemusician"),
    path('updatealbum/<pk>/',views.updatealbum.as_view(),name="updatealbum"),
    path('musiciandelete/<pk>/',views.musiciandelete.as_view(),name="musiciandelete"),
    # path('albumdelete/<pk>/',views.albumdelete.as_view(),name="albumdelete"),



]
urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_DIR,document_root=settings.MEDIA_ROOT)

ClaseBase_CrudProject/first_app/models.py
from django.db import models
from django.urls import reverse,reverse_lazy,path

# Create your models here.
class Musician(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    instrument=models.CharField(max_length=100)
    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.instrument}"
    def get_absolute_url(self):
        return reverse('first_app:index')



class Album(models.Model):
    artist=models.ForeignKey(Musician,on_delete=models.CASCADE,related_name="Album_list")
    album_name=models.CharField(max_length=100,blank=True)
    release_date=models.DateField(null=True)
    numstarts=models.IntegerField(choices=((1,"good"),(2,"better"),(3,"best")))
    def __str__(self):
        return f"{self.album_name} {self.release_date} {self.numstarts}"

    def get_absolute_url(self):
        return reverse('first_app:index')

ClaseBase_CrudProject/first_app/forms.py
from django import forms
from first_app import models

class MusicianForm(forms.ModelForm):
    class Meta():
        model=models.Musician
        fields="__all__"

class AlbumForm(forms.ModelForm):
    class Meta():
        model=models.Album
        exclude=["artist"]

ClaseBase_CrudProject/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import View,CreateView,TemplateView,ListView,DetailView,UpdateView,DeleteView
from first_app import models
from first_app import forms
from django.urls import reverse_lazy
# Create your views here.

class index(ListView):
    context_object_name="Musician_list"
    model=models.Musician
    template_name="first_app/index.html"

class addmusician(CreateView):
    model=models.Musician
    fields="__all__"
    template_name="first_app/addmusician.html"
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context["title"]="Add Musician"
        context["title1"]="Add musician"
        return context
class addalbum(CreateView):
    model=models.Album
    fields="__all__"
    template_name="first_app/addalbum.html"

class Musiciandetails(DetailView):
    context_object_name="musician_list"

    model=models.Musician
    template_name="first_app/musiciandetails.html"
class updatemusician(UpdateView):
    model=models.Musician
    fields="__all__"
    template_name="first_app/updatemusician.html"
class updatealbum(UpdateView):
    model=models.Album
    fields="__all__"
    template_name="first_app/updatealbum.html"
class musiciandelete(DeleteView):
    context_object_name="musician"
    model=models.Musician
    success_url=reverse_lazy('first_app:index')
    template_name="first_app/musiciandelete.html"
# class albumdelete(DeleteView):
#     model=models.Album
#     context_object_name='album'
#     success_url=reverse_lazy('first_app:index')
#     template_name="albumdelete.html"

ClaseBase_CrudProject/first_app/templates/first_app/addalbum.html
{% extends 'first_app/base.html' %}
{% block body_block %}
{{title}}
<form  method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" value="Submit" class="btn btn-sm btn-primary">

</form>
{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/addmusician.html
{% extends 'first_app/base.html' %}
{% block body_block %}
{{title}}
{{title1}}
<form  method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" value="Submit" class="btn btn-sm btn-primary">

</form>
{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
      <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class=" text-light nav-link active" aria-current="page" href="{% url 'first_app:index' %}"> Home </a>
          </li>
          <li class="nav-item">
              <a class=" text-light nav-link active" aria-current="page" href="{% url 'first_app:addmusician' %}"> Musician </a>
          </li>
          <li class="nav-item">
              <a class=" text-light nav-link active" aria-current="page" href="{% url 'first_app:addalbum' %}"> Album </a>
          </li>



        </ul>
      </div>
      </div>
    </div>
  </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
<div class="container">
{% block body_block %}
{% endblock %}
</div>
  </body>
</html>

ClaseBase_CrudProject/first_app/templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>This is our home page</h1>
<h2>This is our Second home page</h2>
{% if Musician_list %}
<table class="table table-primary">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Instruments</th>

  </tr>
  {% for x in Musician_list %}
  <tr>
    <td><a href="{% url 'first_app:Musiciandetails' pk=x.pk %}">{{x.first_name}}</a></td>
    <td><a href="{% url 'first_app:Musiciandetails' pk=x.pk %}">{{x.last_name}}</a></td>
    <td><a href="{% url 'first_app:Musiciandetails' pk=x.pk %}">{{x.instrument}}</a></td>
  </tr>
  {% endfor %}

</table>
{% else %}
<h1> No Musician Has Left </h1>
{% endif %}
{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/musiciandelete.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>Delete{{musician.first_namet}} {{musician.last_name}} {{musician.instrument}} ?</h1>
<form  method="POST">
  {% csrf_token %}
  <input type="submit"value="submit" class="btn btn-sm btn-danger">
  <a class="btn btn-sm btn-success"  href="{% url 'first_app:Musiciandetails' pk=musician.pk %}">Cancel</a>
</form>
{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/musiciandetails.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>Musician Details : </h1>
<p>{{musician_list.first_name}} {{musician_list.last_name}} {{musician_list.instrument}}</p>
<a class="btn btn-sm btn-primary" href="{% url 'first_app:updatemusician' pk=musician_list.pk %}">Update</a>
<a class="btn btn-sm btn-danger" href="{% url 'first_app:musiciandelete' pk=musician_list.pk %}">Delete</a>

<hr>

<ul>
{% for p in musician_list.Album_list.all  %}
  <li><a href="{% url 'first_app:updatealbum' pk=p.pk %}">{{p.album_name}} {{p.release_date}} {{p.numstarts}}</a></li>
{% endfor %}
</ul>
{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/updatealbum.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<form  method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" value="submit" class="btn btn-sm btn-primary">
</form>

{% endblock %}

ClaseBase_CrudProject/first_app/templates/first_app/updatemusician.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<form class=""  method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" value="Submit" class="btn btn-sm btn-primary">
</form>
{% endblock %}